### PR TITLE
end of file,nab salami

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SalmonDE** [comment]
Isn't necessary, depends on how your style is. I prefer to let it blank

**Comment by ghost** [comment]
@SalmonGER  http://www.w3schools.com/php/

**Comment by SalmonDE** [comment]
@RoofyManStar You can do it, sometimes it's even necessary. Example: Putting PHP code inside HTML.
But in this case it is not necessary

**Comment by ghost** [comment]
Ok. @SalmonGER

**Pull request closed without merging**
