### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by SalmonDE**
###### Fixes a bug? Enhancement?
This pull request merges the rewrite branch into the master branch. I'm creating it because I'm nearly done with it.
It is supposed to fix the current issues #42, #43 and #44. But I can't guarantee it yet.

###### Explain! It can't be that hard right...?
 It replaces the old, bad code with some more organized code.

###### It is recommended that you test it before making a pull request.
- [x] Yes

### CODE REVIEW

**Comment by Aericio** [comment]
oh oops pressed wrong button

**Comment by SalmonDE** [comment]
It would be nice if you could test this branch

**Comment by Aericio** [comment]
I can test on a production server, lol. What exactly needs to be tested?

**Comment by SalmonDE** [comment]
@Aericio every single feature and data saving

**Comment by Aericio** [comment]
JSON Provider:
(TESSERACT)
```
[23:26:16] <ERROR> [StatsPE] Unexpected datatype returned "NULL" for entry "OnlineTime" in "SalmonDE\StatsPE\Providers\JSONProvider" by "getData"!
```
(TESSERACT) #46 
```
Notice: Undefined property: SalmonDE\StatsPE\Providers\JSONProvider::$dataProvider in phar:///home/gmplus/Factions/plugins/StatsPE_REWRITE.phar/src/SalmonDE/StatsPE/Providers/JSONProvider.php on line 21
[23:32:52] <CRITICAL> "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'StatsPE v3.2.1': Call to a member function getEntries() on null on SalmonDE\StatsPE\EventListener
[23:32:52] <CRITICAL> Error: "Call to a member function getEntries() on null" (EXCEPTION) in "/StatsPE_REWRITE.phar/src/SalmonDE/StatsPE/Providers/JSONProvider" at line 21
```

**Comment by Aericio** [comment]
/statspe:
image

**Pull request merged**
