### PR TITLE
Add Russian lang :D

### PR DESCRIPTION
**Pull request by daniktheboss**
### General

Add russian lang

**Explain** why this Pull Request should be merged:
Well, adds russian lang
### Extra Information

adds russian lang

reread like 3 times

### CODE REVIEW

**Comment by SalmonDE** [comment]
:+1:

**Comment by daniktheboss** [comment]
Hey when I change lang in config to any other language it's still english

**Comment by SalmonDE** [comment]
@daniktheboss Did you delete the messages.ini afterwards?

**Comment by daniktheboss** [comment]
Oh well... no 😂 ok thanks

**Comment by daniktheboss** [comment]
Add that to the config next to lang pls

**Comment by Aericio** [comment]
Ok ;)

**Comment by daniktheboss** [comment]
Add the instructions to delete messages.ini in order to install new lang

**Pull request merged**
