### PR TITLE
Add plugin events

### PR DESCRIPTION
**Pull request by SalmonDE**
#### **What does the PR do?**
It adds events to the plugin which makes external plugins more able to interfer with StatsPE and react to situations. 

Edit:
It also removes the auto update feature so it won't get problems with Poggit anymore.
Version checking is still implemented.

#### **Why should this PR be merged?**
There normally shouldn't be any difference in behaviour, as stated above it's mainly for other plugins which need this. 

#### **Are the changes in this PR tested**?

- [ ] Yes
- [x] Partly (JSON)
- [ ] No

#### **Extra Information**

JSON was tested to the bare minimum and MySQL wasn't at all.
So MySQL needs testing, while JSON seems to be stable but could also be tested more further.

### CODE REVIEW

**Comment by Aericio** [comment]
Need me to test mysql?

**Comment by SalmonDE** [comment]
@Aericio yes please

**Comment by Aericio** [comment]
@SalmonDE ok bb

**Comment by SalmonDE** [comment]
Events work, external plugins can listen for them. Completed testing for json.

**Comment by SalmonDE** [comment]
I guess no issues anymore @Aericio ?

**Comment by Aericio** [comment]
Sorry, forgot about this :P
When I try to craft anything:
image
image
Startup (PMMP):
image
reason why not testing on pmmp: keeps blocking me after crafting something :/
image

**Comment by SalmonDE** [comment]
I never knew you could craft so much that you reach the limit 2147483647.
I'm going to make it use bigint as datatype and make it unsigned, increasing the limit to 18446744073709551615

**Comment by SalmonDE** [comment]
@Aericio You'd want to let the plugin generate a new table to use bigints.

**Comment by Aericio** [comment]
> I never knew you could craft so much that you reach the limit 2147483647.

Probably something with crafting.. I only turned a stack of wood to planks and it made it that big. I think it's just the cores problem with crafting.

**Comment by Aericio** [comment]
image
```
[17:22:57] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\inventory\CraftItemEvent' to 'StatsPE v3.4.1': Argument 3 passed to SalmonDE\StatsPE\Providers\MySQLProvider::incrementValue() must be of the type integer, float given, called in C:\Users\Aericio\Desktop\Minecraft PE\plugins\StatsPE-events\src\SalmonDE\StatsPE\EventListener.php on line 137 on SalmonDE\StatsPE\EventListener
[17:22:57] [Server thread/CRITICAL]: TypeError: "Argument 3 passed to SalmonDE\StatsPE\Providers\MySQLProvider::incrementValue() must be of the type integer, float given, called in C:\Users\Aericio\Desktop\Minecraft PE\plugins\StatsPE-events\src\SalmonDE\StatsPE\EventListener.php on line 137" (EXCEPTION) in "/StatsPE-events/src/SalmonDE/StatsPE/Providers/MySQLProvider" at line 144
```
Have that now. Why the item count is so big... no idea lol. Maybe there is crafting async or something? Check telegram, I sent you a video.

**Review by Aericio — APPROVED** [review]
Hooray! Everything seems fine after testing for me, there is no more issue with craft count going to infinity.

**Pull request merged**
