### PR TITLE
Language

### PR DESCRIPTION
**Pull request by ghost**
Useless Commit

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Shut up NycuRo

**Comment by thebigsmileXD** [comment]
Also 100% accurate fix.

**Comment by RoofyManStar** [comment]
Man , @thebigsmileXD and @Aericio . CORRECT IS STATS. Omg nabs......

**Comment by RoofyManStar** [comment]
@SalmonGER Salami,aericio is nab, wtf. Watch and link :/

**Comment by SalmonDE** [comment]
Stop calling us "nabs", we are sure it's like that.

**Pull request closed without merging**
