### PR TITLE
@Salmonger $sender is instanceof Player :/ not all

### PR DESCRIPTION
**Pull request by ghost**
nab salami. $sender is instanceof Player,not console or other. You can use $player for more exactly.

### CODE REVIEW

**Comment by SalmonDE** [comment]
$player is not a defined variable at that place! $sender is right, you can test /floatingstats

**Comment by ghost** [comment]
@SalmonGER Yes,is. You can test.

**Comment by SalmonDE** [comment]
@RoofyManStar I did, works for me

**Comment by ghost** [comment]
@SalmonGER Man, $player is correct,lol.

**Comment by SalmonDE** [comment]
Your changes crashed the server

**Pull request closed without merging**
