### PR TITLE
#hatetrain

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by caspervanneck** [comment]
fuck nycuro and apollo i hate you its time for revange

**Comment by caspervanneck** [comment]
what we do is bad but now is it time to wipe his ass

**Comment by thebigsmileXD** [comment]
whats ur problem m8

**Comment by caspervanneck** [comment]
now i wanth to kil him im realy angry

**Comment by caspervanneck** [comment]
rong buton

**Comment by caspervanneck** [comment]
fuck nycuro and apollo

**Comment by caspervanneck** [comment]
@thebigsmileXD  everting i whant revange

**Comment by caspervanneck** [comment]
.

**Comment by caspervanneck** [comment]
fuck it

**Comment by SwagGermany** [comment]
Calm down bro

**Comment by SalmonDE** [comment]
Ok, ok, you can get revenge but not here, this is not NycuROs plugin.

**Comment by Aericio** [comment]
Deleted messages.

**Pull request closed without merging**
